version = 1

test_patterns = [
    "*/test/**",
    "*/test_runners/**"
]

exclude_patterns = ["example/**"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"